name: gen-check

on: [push, pull_request]

jobs:
  gen-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run gen-check target
      run: |
        make gen-check
